### PR TITLE
LRDOCS-10630 Improvements to Validations Documentation

### PR DESCRIPTION
**Pull request by JamesAGarcia**
This PR updates Validations documentation, per [LRDOCS-10630](https://issues.liferay.com/browse/LRDOCS-10630). 

To @djangotti: 
1. Is it appropriate to use 'valid'/'invalid' with [these validation examples](https://github.com/JamesAGarcia/liferay-learn/blob/bcbba9ef51e7eeadf478b31b7a46da5068c09b52/docs/dxp/latest/en/building-applications/objects/creating-and-managing-objects/expression-builder-validations-reference.md#validation-examples)? 
1. Should I update [line 59](https://github.com/JamesAGarcia/liferay-learn/compare/master...JamesAGarcia:LRDOCS-10630?expand=1#diff-462b117582c3367fc0c2379652680b9163788beebf0a49cd33250482c6d3dfaeR59) about Groovy validations?
1. Should I expand on [line 69](https://github.com/JamesAGarcia/liferay-learn/compare/master...JamesAGarcia:LRDOCS-10630?expand=1#diff-462b117582c3367fc0c2379652680b9163788beebf0a49cd33250482c6d3dfaeR69)? For example, is there a `invalidFields` variable in the background that's assigned true or false depending on the validation's conditions?
1. I added two simple tables to the end of the Adding Custom Validations article. One for [operators](https://github.com/JamesAGarcia/liferay-learn/blob/bcbba9ef51e7eeadf478b31b7a46da5068c09b52/docs/dxp/latest/en/building-applications/objects/creating-and-managing-objects/adding-custom-validations.md#expression-builder-operators) and one for [functions](https://github.com/JamesAGarcia/liferay-learn/blob/bcbba9ef51e7eeadf478b31b7a46da5068c09b52/docs/dxp/latest/en/building-applications/objects/creating-and-managing-objects/adding-custom-validations.md#expression-builder-functions). Let me know if you'd like me to remove or relocate them. 
1. I noticed the [Condition function](https://github.com/JamesAGarcia/liferay-learn/compare/master...JamesAGarcia:LRDOCS-10630?expand=1#diff-462b117582c3367fc0c2379652680b9163788beebf0a49cd33250482c6d3dfaeR136). I forget: is this one explained anywhere?

### CODE REVIEW

**Comment by djangotti** [comment]
Hi @JamesAGarcia,

Here are the answers:

1. Is it appropriate to use 'valid'/'invalid' with [these validation examples](https://github.com/JamesAGarcia/liferay-learn/blob/bcbba9ef51e7eeadf478b31b7a46da5068c09b52/docs/dxp/latest/en/building-applications/objects/creating-and-managing-objects/expression-builder-validations-reference.md#validation-examples)?
**A:** When discussed with the team, they suggest (and I really understand) that can be better if we use true/false because a valid/invalid value can be interpretative.

2. Should I update [line 59](https://github.com/JamesAGarcia/liferay-learn/compare/master...JamesAGarcia:LRDOCS-10630?expand=1#diff-462b117582c3367fc0c2379652680b9163788beebf0a49cd33250482c6d3dfaeR59) about Groovy validations?
**A:** Maybe, my 2 cents here is to change this sentence ("This variable should return `true` for invalid field values and `false` for valid field values.") to:  "This variable should return `true` when the script creator wants to show the message error and `false` for a valid script that works correctly." It is just an idea, I'm not as good with words as you are. kkkk

3. Should I expand on [line 69](https://github.com/JamesAGarcia/liferay-learn/compare/master...JamesAGarcia:LRDOCS-10630?expand=1#diff-462b117582c3367fc0c2379652680b9163788beebf0a49cd33250482c6d3dfaeR69)? For example, is there a invalidFields variable in the background that's assigned true or false depending on the validation's conditions?
**A:** No, we do not have.

4. I added two simple tables to the end of the Adding Custom Validations article. One for [operators](https://github.com/JamesAGarcia/liferay-learn/blob/bcbba9ef51e7eeadf478b31b7a46da5068c09b52/docs/dxp/latest/en/building-applications/objects/creating-and-managing-objects/adding-custom-validations.md#expression-builder-operators) and one for [functions](https://github.com/JamesAGarcia/liferay-learn/blob/bcbba9ef51e7eeadf478b31b7a46da5068c09b52/docs/dxp/latest/en/building-applications/objects/creating-and-managing-objects/adding-custom-validations.md#expression-builder-functions). Let me know if you'd like me to remove or relocate them.
**A:** Great idea! Amazing! Looking for this table, on the Sierra public channel, we received a suggestion to change Times to Multiply. Sounds better to me, what do you think? Can we change?

5. I noticed the [Condition function](https://github.com/JamesAGarcia/liferay-learn/compare/master...JamesAGarcia:LRDOCS-10630?expand=1#diff-462b117582c3367fc0c2379652680b9163788beebf0a49cd33250482c6d3dfaeR136). I forget: is this one explained anywhere?
**A:** No James, we do not have :(. Here is what I thought about it: "Provide for the customer the possibility of condition for values or fields and determines if expressions are true or false. Returns a given value if true and another value if false." What do you think?
Conditions can be used with text, numeric, and date fields.

**Comment by JamesAGarcia** [comment]
@djangotti Thank you for your input. I've updated the articles per your feedback.

However, I am still unsure how the Condition function works.

I see that the syntax is `condition(condition, parameter1, parameter2)`, however, I don't understand the second use of condition here--the one inside the parentheses. Am I supposed to replace it with something, just like I'm supposed to replace `parameter1` and `parameter2` with text, numeric, or dates?
A concrete example would help.

**Comment by djangotti** [comment]
Hi @JamesAGarcia

Conditions work as an "if" statement. 
So it is possible to define the condition itself like textField_name == "James", and for that code return parameters as a conditional return. I record this [video](https://drive.google.com/file/d/1EAghBPsgMlSgixlsak1WuCV4KrIYEpJr/view?usp=sharing) a time ago, can help. 

These are a "real" code examples:
- `condition(ticketType == "behaviorClarification", ticketPriority != "high", true)`
- `condition(ticketType != "behaviorClarification", true, false)`
- `condition(ticketPriority != "high", true, false)`
- `condition(ticketId == "LRDOCS-10630", false, true)`

If I did not make myself clear, let's discuss.
Thank you James :)

**Comment by JamesAGarcia** [comment]
@djangotti Thank you! I believe you answered all my questions. 

Does this seem clear and accurate?
>Check if user input meets one or more conditions and return a boolean value. This function works like `if` statements. Each expression includes at least one `<condition>` (e.g., `<textField> == "foo"`) and returns `true` or `false`. You can add multiple conditions to the same expression and determine a return value if none of the conditions are met (e.g., `<textField> == "foo", <textField> == "bar", true, false`).

Just let me know if you'd like me to revise or add anything.

**Comment by djangotti** [comment]
Hi @JamesAGarcia,

Amazing! We can move forward with this LRDOCS-10630. :)

Thank you so much!!

**Pull request closed without merging**
