### PR TITLE
LRDOCS-10481 & LRDOCS-10548 & LRDOCS-10584 adds Extending System Objects

### PR DESCRIPTION
**Pull request by JamesAGarcia**
This PR adds an Extending System Objects article, per [LRDOCS-10481](https://issues.liferay.com/browse/LRDOCS-10481), [LRDOCS-10548](https://issues.liferay.com/browse/LRDOCS-10548), and [LRDOCS-10584](https://issues.liferay.com/browse/LRDOCS-10584). It also updates related content in other articles.

@djangotti, Looking at [these release notes](https://liferay.atlassian.net/wiki/spaces/TEAMRM/pages/2053111878/Release+Highlights+-+DXP+7.4+Update+30+GA+30), it looks like the Many to Many relationship for system Objects will be released U30/GA30. Is this correct?

### CODE REVIEW

**Comment by djangotti** [comment]
Hi @JamesAGarcia,

Yes, Many to Many relationships for system Objects will be released U30/GA30. :)

**Comment by JamesAGarcia** [comment]
@djangotti Thank you for clarifying and correcting my misunderstanding 🙌🏼

**Comment by JamesAGarcia** [comment]
@djangotti I updated the version and removed/commented out the inaccurate information.

**Comment by djangotti** [comment]
Thank you @JamesAGarcia!!!!

**Pull request closed without merging**
