### PR TITLE
LRDOCS-10171 adds Hreflang config article w/imgs

### PR DESCRIPTION
**Pull request by JamesAGarcia**
This PR adds a new article on the new _Enable Only Translated Hreflangs_ setting for Instances and Sites, per [LRDOCS-10171](https://issues.liferay.com/browse/LRDOCS-10171).

@AliciaGarciaGarcia Question: How do the two methods for configuring Site settings relate to one another? 
For example, if I enable this new behavior for a Site via the Site Menu, my configuration doesn't show up in the Global Menu, or vice versa. Is this the expected intended behavior?

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
Hi @JamesAGarcia 
If you make changes on the global menu > Site scope, the changes should be reflected in the settings of the site settings menu.
BUT if you make changes on the site settings menu then this override and will be independent from the global menu settings.
To restore the first behavior and the changes are synchronized between both menus, we must restore the site settings values to default on the three points menu on the upper right.

**Comment by JamesAGarcia** [comment]
> If you make changes on the global menu > Site scope, the changes should be reflected in the settings of the site settings menu. BUT if you make changes on the site settings menu then this override and will be independent from the global menu settings. To restore the first behavior and the changes are synchronized between both menus, we must restore the site settings values to default on the three points menu on the upper right.

@AliciaGarciaGarcia Thank you for clarifying! I was wondering: should we recommend one context for configuration over another? I'm wondering if this behavior could create some confusion for users.

**Comment by AliciaGarciaGarcia** [comment]
@JamesAGarcia

This behavior it's the common with the site settings.
 But it's a question that I can not answer. It's better to check this with Pablo for a more accurate response

**Comment by JamesAGarcia** [comment]
@AliciaGarciaGarcia Good to know--thank you, again! I'll reach out to Pablo for clarification.

**Pull request closed without merging**
